#!/bin/bash
# lookup default hosts or host supplied from domain provided

lookup_host () {
dig "$2"."$1" | grep ^"$2" |\
    awk -v subd="$2" '{print "The subdomain "subd" is a "$4" record and points to "$5}'
}

if [ "$#" == 1 ]
  then
    subds="www lb-01 web-01 web-02"
  else
    subds="$2"
fi

for i in ${subds} 
do 
    lookup_host "$1" "$i"
done
