#!/usr/bin/env bash
# install nginx and set default webpage

apt-get update
apt-get -y install nginx
ufw allow http 

sed 's/Welcome\ to/Holberton/g;s/nginx\!/School/g' \
 /var/www/html/index.nginx-debian.html > /var/www/html/index.html

service nginx restart
