#!/usr/bin/env bash
# install nginx, set default webpage, and set redirect

apt-get update
apt-get -y install nginx
ufw allow http 

sed 's~Welcome\ to~Holberton~g;s~nginx\!~School~g' \
 /var/www/html/index.nginx-debian.html > /var/www/html/index.html

sed -i 's~^}~\n\trewrite ^/redirect_me http://www.rawilson.com/quantum.html permanent;\n\n}~' /etc/nginx/sites-available/default

service nginx restart
