#!/usr/bin/env bash
# there's got to be a better way..., yeeaah

exec 3< /etc/passwd

while read -u 3 -r line
 do

    echo "The user $(echo "$line" | cut -d: -f1) is part of the $(echo "$line" | cut -d: -f4) gang, lives in $(echo "$line" | cut -d: -f6) and rides $(echo "$line" | cut -d: -f7). $(echo "$line" | cut -d: -f3)'s place is protected by the passcode $(echo "$line" | cut -d: -f2), more info about the user here: $(echo "$line" | cut -d: -f5)"

done

exec 3<&-
