#!/usr/bin/env bash
# print string 10 times adding Hi on new line after 9th iteration

i=0 # 0 index

while [ $i -lt 10 ]

 do

    echo "Holberton School"

    if [ $i == 8 ] # 9th iteration
     then

        echo "Hi"

    fi

    i=$((i + 1))

done

