#!/usr/bin/env bash
# print 1 through 20 subbing messages for 3 unlucky numbers

i=1 # 1 index

while [ $i -le 20 ]

 do

    echo $i

    case $i in
     4)
       echo "bad luck from China"
       ;;
     9)
       echo "bad luck from Japan"
       ;;
     17)
       echo "bad luck from Italy"
       ;;
    esac

    i=$((i + 1))

done

