#!/usr/bin/env bash
# print every 59 minutes for 0-12 (13) hours

h=0
m=1

while [ $h -le 12 ]
 do

    echo "Hour: $h"

    while [ $m -le 59 ]
     do

        echo $m

        m=$((m + 1))

    done

    m=1

    h=$((h + 1))

done

