#!/usr/bin/env bash
# run nginx as non-privileged user
pkill -f apache2
sed -i '/^[[:blank:]]*listen.*[ :]80\ /s/80.*default.*;$/8080\  default_server;/' /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
su -c 'service nginx start' nginx
